version: "3.9"

services:
  web:
    build: .
    command: poetry run gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - djangotutorial/mysite/.env
